### ISSUE TITLE
Yarn doesn't match Node version

### ISSUE THREAD

**Issue by grossbart** [kaitanie/nix-purescript-example-project#1]
I just saw this repo on Twitter and wanted to draw your attention to a mistake I've made in the past: the way you add Yarn to `buildInputs` it will be bound to whatever Node version is the current version (`pkgs.nodejs`), not the one you specified.

https://github.com/kaitanie/nix-purescript-example-project/blob/3c377ac5aa5129ac9411491f241a86077e9d64cf/default.nix#L11

Here's how you can override the Node version Yarn should be built against:

```
let
  unpinned = import <nixpkgs> {};
in
{ pkgs ? import (unpinned.fetchFromGitHub
  { owner = "NixOS";
    repo = "nixpkgs";
    rev = "c26b40a933ea2b7fa4ca1fdc6900d54d726e73ff";
    sha256 = "1j1f0n7rl8vq91af9hrf98f98f449yr5i0p540q8gbsr504qid8b";
  }) {}
}:

let
  nodejs = pkgs.nodejs-10_x;
  yarn = pkgs.yarn.override { inherit nodejs; };

in pkgs.stdenv.mkDerivation rec {
  name = "example";
  buildInputs = [
    nodejs
    yarn
  ];
}

```

**Comment by kaitanie** [comment]
Thanks for reporting the problem! I fixed the issue. I also added the same override for nodePackages  and that seems to make bower use the specified Node version too.
